### ISSUE TITLE
bug du site

### ISSUE THREAD

**Issue by simonNolf** [Austreelis/WebsiteWhereYouAreTheHero#48]
![image](https://user-images.githubusercontent.com/63592563/165254717-8596c92f-df5b-4706-a8ac-3aed0b80bff9.png)

ca apparait quand je vuex me connecter au site

**Comment by Austreelis** [comment]
`npm ci && npm run build` solves the issue. Maybe we could catch that ahead an give a more meaningful error, but I suppose that's a trivial error and won't bother improving on that.
